In [22]:
import jax.random as jrn
import jax.numpy as jnp
import random

from game.run import dummy_history

In [29]:
key = jrn.PRNGKey(random.randint(0, 1000))
batched_history = dummy_history(key, 5, 30)

history = {}

for k, v in batched_history.items():
    history[k] = v[-1]


history["winner"]

Array([[False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]], dtype=bool)

In [37]:
history["winner"][-1, 0]

history["roles"][-1]

Array([0, 1, 0, 0, 2], dtype=int32)

In [39]:
def vote_data(winner, voted, roles, player: int = 1, **_):
    """
    """
    role = roles[0, player]

    wins = winner[0]

    # 0: no winner, 1: L win, 2: F win
    wins = wins.argmax() + wins.sum()


    acts = voted[:, player]

    return wins, acts, role


vote_data(**history)

(Array(2, dtype=int32),
 Array([False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True], dtype=bool),
 Array(1, dtype=int32))