In [46]:
import jax.random as jrn
import jax.numpy as jnp
import jax
import random

from game.run import dummy_history

In [29]:
key = jrn.PRNGKey(random.randint(0, 1000))
batched_history = dummy_history(key, 5, 30)

history = {}

for k, v in batched_history.items():
    history[k] = v[-1]


history["winner"]

Array([[False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]], dtype=bool)

In [37]:
history["winner"][-1, 0]

history["roles"][-1]

Array([0, 1, 0, 0, 2], dtype=int32)

In [47]:
@jax.jit
def vote_data(winner, voted, roles, player: int = 1, **_):
    """
    """
    role = roles[0, player]
    role = role != 0 # only check if L

    wins = winner[0]

    # 0: no winner, 1: L win, 2: F win
    wins = wins.argmax() + wins.sum()

    acts = voted[:, player].astype(jnp.int32)
    rang = jnp.arange(acts.shape[0])

    data = jnp.zeros((*acts.shape, 2))
    data = data.at[rang, acts].set(1)

    return wins, acts, role, data


vote_data(**history)

(Array(2, dtype=int32),
 Array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 1], dtype=int32),
 Array(True, dtype=bool),
 Array([[1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]], dtype=float32))

In [ ]:
# model(**history, acts=acts, role=role) -> wins